import tkinter.ttk
from tkinter import *

root = Tk()
root.state('zoomed')
root.title('Financial Analysis Software')
name_label = Label(root, text='Financial Analysis', bg='orange', font=10, height=3, width=140)
name_label.grid(row=0, column=0)

# tabs
style = tkinter.ttk.Style()
current_theme = style.theme_use()
style.theme_settings(current_theme, {'TNotebook.Tab': {'configure': {'padding': [40, 5]}}})
style.configure('TNotebook.Tab', background='orange')
style.map('TNotebook', background=[('selected', 'orange')])
tabs = tkinter.ttk.Notebook()
tabs.grid(row=1, column=0)
data_frame = Frame(tabs, highlightbackground='orange', highlightthickness=3, height=680, width=1515)
comparative_frame = Frame(tabs, highlightbackground='orange', highlightthickness=3, height=680, width=1515)
common_frame = Frame(tabs, highlightbackground='orange', highlightthickness=3, height=680, width=1515)
ratio_frame = Frame(tabs, highlightbackground='orange', highlightthickness=3, height=680, width=1515)
trend_frame = Frame(tabs, highlightbackground='orange', highlightthickness=3, height=680, width=1515)
tabs.add(data_frame, text='Data')
tabs.add(comparative_frame, text='Comparative Statement')
tabs.add(common_frame, text='Common size Statement')
tabs.add(ratio_frame, text='Ratios')
tabs.add(trend_frame, text='Trend Analysis')

company_frame = Frame(data_frame, highlightbackground='orange', highlightthickness=2, height=50, width=1510)
company_frame.place(x=0, y=0)
company_label = Label(company_frame, text='Enter Company name :')
company_label.place(x=10, y=10)
company_entry = Entry(company_frame, width=50)
company_entry.place(x=150, y=12)
year_label = Label(company_frame, text='Year :')
year_label.place(x=1095, y=10)
year_entry = Entry(company_frame, width=50)
year_entry.place(x=1145, y=10)

# Profit and loss statement data
p_l_frame = Frame(data_frame, highlightbackground='orange', highlightthickness=2, height=550, width=760)
p_l_frame.place(x=0, y=50)
p_l_label = Label(p_l_frame, text='Statement of Profit and Loss Data', bg='orange', width=108)
p_l_label.place(x=0, y=0)
rfo_label = Label(p_l_frame, text='Revenue from Operations :')
rfo_label.place(x=5, y=30)
rfo_entry = Entry(p_l_frame, width=40)
rfo_entry.place(x=320, y=30)
oi_label = Label(p_l_frame, text='Other Income :')
oi_label.place(x=5, y=60)
oi_entry = Entry(p_l_frame, width=40)
oi_entry.place(x=320, y=60)
com_label = Label(p_l_frame, text='Cost of Materials :')
com_label.place(x=5, y=90)
com_entry = Entry(p_l_frame, width=40)
com_entry.place(x=320, y=90)
purchase_label = Label(p_l_frame, text='Purchases :')
purchase_label.place(x=5, y=120)
purchase_entry = Entry(p_l_frame, width=40)
purchase_entry.place(x=320, y=120)
cii_label = Label(p_l_frame, text='Change in Inventory :')
cii_label.place(x=5, y=150)
cii_entry = Entry(p_l_frame, width=40)
cii_entry.place(x=320, y=150)
ebe_label = Label(p_l_frame, text='Employee Benefit Expenses :')
ebe_label.place(x=5, y=180)
ebe_entry = Entry(p_l_frame, width=40)
ebe_entry.place(x=320, y=180)
fc_label = Label(p_l_frame, text='Finance Cost :')
fc_label.place(x=5, y=210)
fc_entry = Entry(p_l_frame, width=40)
fc_entry.place(x=320, y=210)
dna_label = Label(p_l_frame, text='Depreciation and Amortization :')
dna_label.place(x=5, y=240)
dna_entry = Entry(p_l_frame, width=40)
dna_entry.place(x=320, y=240)
ode_label = Label(p_l_frame, text='Other Direct expenses :')
ode_label.place(x=5, y=270)
ode_entry = Entry(p_l_frame, width=40)
ode_entry.place(x=320, y=270)
oie_label = Label(p_l_frame, text='Other Indirect Expenses :')
oie_label.place(x=5, y=300)
oie_entry = Entry(p_l_frame, width=40)
oie_entry.place(x=320, y=300)
tax_label = Label(p_l_frame, text='Tax :')
tax_label.place(x=5, y=330)
tax_entry = Entry(p_l_frame, width=40)
tax_entry.place(x=320, y=330)

# Balance sheet data
b_s_frame = Frame(data_frame, highlightbackground='orange', highlightthickness=2, height=550, width=750)
b_s_frame.place(x=760, y=50)
b_s_label = Label(b_s_frame, text='Balance Sheet Data', bg='orange', width=108)
b_s_label.place(x=0, y=0)
share_fund_label = Label(b_s_frame, text='Shareholders Fund :')
share_fund_label.place(x=0, y=40)
share_fund_entry = Entry(b_s_frame, width=40)
share_fund_entry.place(x=320, y=30)
ltb_label = Label(b_s_frame, text='Long Term Borrowings :')
ltb_label.place(x=0, y=60)
ltb_entry = Entry(b_s_frame, width=40)
ltb_entry.place(x=320, y=60)
fta_label = Label(b_s_frame, text='Fixed Tangible Asset :')
fta_label.place(x=0, y=90)
fta_entry = Entry(b_s_frame, width=40)
fta_entry.place(x=320, y=90)
fia_label = Label(b_s_frame, text='Fixed Intangible Asset :')
fia_label.place(x=0, y=120)
fia_entry = Entry(b_s_frame, width=40)
fia_entry.place(x=320, y=120)
lti_label = Label(b_s_frame, text='Long Term Investments :')
lti_label.place(x=0, y=150)
lti_entry = Entry(b_s_frame, width=40)
lti_entry.place(x=320, y=150)
ltl_label = Label(b_s_frame, text='Long Term Loans (Asset) :')
ltl_label.place(x=0, y=180)
ltl_entry = Entry(b_s_frame, width=40)
ltl_entry.place(x=320, y=180)
ola_label = Label(b_s_frame, text='Other Long Term Assets :')
ola_label.place(x=0, y=210)
ola_entry = Entry(b_s_frame, width=40)
ola_entry.place(x=320, y=210)
inv_label = Label(b_s_frame, text='Inventory :')
inv_label.place(x=0, y=240)
inv_entry = Entry(b_s_frame, width=40)
inv_entry.place(x=320, y=240)
tr_label = Label(b_s_frame, text='Trade Receivables :')
tr_label.place(x=0, y=270)
tr_entry = Entry(b_s_frame, width=40)
tr_entry.place(x=320, y=270)
ci_label = Label(b_s_frame, text='Current Investment :')
ci_label.place(x=0, y=300)
ci_entry = Entry(b_s_frame, width=40)
ci_entry.place(x=320, y=300)
cac_label = Label(b_s_frame, text='Cash and Cash Equivalents :')
cac_label.place(x=0, y=330)
cac_entry = Entry(b_s_frame, width=40)
cac_entry.place(x=320, y=330)
oca_label = Label(b_s_frame, text='Other Current Assets :')
oca_label.place(x=0, y=360)
oca_entry = Entry(b_s_frame, width=40)
oca_entry.place(x=320, y=360)

# Data button frame and buttons
data_button_frame = Frame(data_frame, highlightbackground='orange', highlightthickness=3, height=75, width=1510)
data_button_frame.place(x=0, y=600)
upload_button = Button(data_button_frame, text='Upload Data', height=2, width=30)
upload_button.place(x=260, y=15)
clear_button = Button(data_button_frame, text='Clear Data', height=2, width=30)
clear_button.place(x=1000, y=15)

# Comparative statement, frames and radio buttons
comparative_label = Label(comparative_frame, text='Comparative Statement', bg='orange', height=1, width=220)
comparative_label.place(x=0, y=0)
comp_p_l_frame = Frame(comparative_frame, highlightbackground='orange', highlightthickness=3, height=600, width=755)
comp_p_l_frame.place(x=0, y=75)
comp_p_l_label = Label(comp_p_l_frame, text='Comparative Profit and Loss Statement', bg='orange', height=1, width=110)
comp_p_l_label.place(x=0, y=1)
comp_bs_frame = Frame(comparative_frame, highlightbackground='orange', highlightthickness=3, height=600, width=755)
comp_bs_frame.place(x=755, y=75)
comp_bs_label = Label(comp_bs_frame, text='Comparative BalanceSheet', bg='orange', height=1, width=110)
comp_bs_label.place(x=0, y=1)

comp_var = IntVar()
comp_r1 = Radiobutton(comparative_frame, text='Year 1-2', font=(None, 10), variable=comp_var, value=1)
comp_r1.place(x=0, y=35)
comp_r1.select()
comp_r2 = Radiobutton(comparative_frame, text='Year 2-3', font=(None, 10), variable=comp_var, value=2)
comp_r2.place(x=120, y=35)
comp_r3 = Radiobutton(comparative_frame, text='Year 3-4', font=(None, 10), variable=comp_var, value=3)
comp_r3.place(x=240, y=35)
comp_r4 = Radiobutton(comparative_frame, text='Year 4-5', font=(None, 10), variable=comp_var, value=4)
comp_r4.place(x=360, y=35)
comp_r5 = Radiobutton(comparative_frame, text='Year 5-6', font=(None, 10), variable=comp_var, value=5)
comp_r5.place(x=480, y=35)

# Common size statement, frames and radio buttons
common_label = Label(common_frame, text='Common Size Statement', bg='orange', height=1, width=220)
common_label.place(x=0, y=0)
common_p_l_frame = Frame(common_frame, highlightbackground='orange', highlightthickness=3, height=600, width=755)
common_p_l_frame.place(x=0, y=75)
common_p_l_label = Label(common_p_l_frame, text='Common Size Profit and Loss Statement', bg='orange',
                         height=1, width=110)
common_p_l_label.place(x=0, y=1)
common_bs_frame = Frame(common_frame, highlightbackground='orange', highlightthickness=3, height=600, width=755)
common_bs_frame.place(x=755, y=75)
common_bs_label = Label(common_bs_frame, text='Common Size BalanceSheet Statement', bg='orange', height=1, width=110)
common_bs_label.place(x=0, y=1)

common_var = IntVar()
common_var1 = Radiobutton(common_frame, text='Year 1', font=(None, 10), variable=common_var, value=1)
common_var1.place(x=0, y=35)
common_var1.select()
common_var2 = Radiobutton(common_frame, text='Year 2', font=(None, 10), variable=common_var, value=2)
common_var2.place(x=120, y=35)
common_var3 = Radiobutton(common_frame, text='Year 3', font=(None, 10), variable=common_var, value=3)
common_var3.place(x=240, y=35)
common_var4 = Radiobutton(common_frame, text='Year 4', font=(None, 10), variable=common_var, value=4)
common_var4.place(x=360, y=35)
common_var5 = Radiobutton(common_frame, text='Year 5', font=(None, 10), variable=common_var, value=5)
common_var5.place(x=480, y=35)
common_var6 = Radiobutton(common_frame, text='Year 6', font=(None, 10), variable=common_var, value=6)
common_var6.place(x=600, y=35)

# Trend frame and components
trend_button_frame = Frame(trend_frame, bg='orange', highlightbackground='orange', highlightthickness=3,
                           width=325, height=675)
trend_button_frame.place(x=0, y=0)
rfo_trend_button = Button(trend_button_frame, text='Revenue From Operations', width=44, height=3)
rfo_trend_button.place(x=0, y=0)
gp_trend_button = Button(trend_button_frame, text='Gross Profit', width=44, height=3)
gp_trend_button.place(x=0, y=98)
op_trend_button = Button(trend_button_frame, text='Operating Profit', width=44, height=3)
op_trend_button.place(x=0, y=196)
np_trend_button = Button(trend_button_frame, text='Net Profit', width=44, height=3)
np_trend_button.place(x=0, y=294)
debt_trend_button = Button(trend_button_frame, text='Debt', width=44, height=3)
debt_trend_button.place(x=0, y=392)
ox_button = Button(trend_button_frame, text='Operating Expenses', width=44, height=3)
ox_button.place(x=0, y=490)
trend_table_frame = Frame(trend_frame, highlightbackground='orange', highlightthickness=3, width=1185, height=320)
trend_table_frame.place(x=325, y=0)
trend_graph_frame = Frame(trend_frame, highlightbackground='orange', highlightthickness=3, width=1185, height=350)
trend_graph_frame.place(x=325, y=325)

# Ratio frames and components
ratio_option_frame = Frame(ratio_frame, bg='orange', highlightbackground='orange', highlightthickness=3, width=325,
                           height=675)
ratio_option_frame.place(x=0, y=0)
liquidity_ratio = StringVar()
liquidity_ratio.set('Liquidity Ratios')
liquidity_list = ['Current Ratio', 'Quick Ratio', 'Cash Ratio']
liquidity_menu = OptionMenu(ratio_option_frame, liquidity_ratio, *liquidity_list)
liquidity_menu.configure(width=46, height=3)
liquidity_menu.place(x=0, y=0)

solvency_ratio = StringVar()
solvency_ratio.set('Solvency Ratios')
solvency_list = ['Debt to Equity Ratio', 'Debt to Capital Employed Ratio', 'Proprietary Ratio',
                 'Interest Coverage Ratio']
solvency_menu = OptionMenu(ratio_option_frame, solvency_ratio, *solvency_list)
solvency_menu.configure(width=46, height=3)
solvency_menu.place(x=0, y=98)

profitability_ratio = StringVar()
profitability_ratio.set('Profitability Ratios')
profitability_list = ['Gross Profit Ratio', 'Operating Ratio', 'Operating Profit Ratio', 'Net Profit Ratio',
                      'Return on Investment Ratio', 'Return on Networth Ratio', 'Earnings Per Share',
                      'Book Value Per Share', 'Dividend Payout Ratio', 'Price Earning Ratio']
profitability_menu = OptionMenu(ratio_option_frame, profitability_ratio, *profitability_list)
profitability_menu.configure(width=46, height=3)
profitability_menu.place(x=0, y=196)

turnover_ratio = StringVar()
turnover_ratio.set('Turnover Ratios')
turnover_list = ['Inventory Turnover Ratio', 'Debtors Turnover Ratio', 'Creditors Turnover Ratio',
                 'Capital Turnover Ratio', 'Fixed Asset Turnover Ratio', 'Working Capital Turnover Ratio']
turnover_menu = OptionMenu(ratio_option_frame, turnover_ratio, *turnover_list)
turnover_menu.configure(width=46, height=3)
turnover_menu.place(x=0, y=294)
ratio_table_frame = Frame(ratio_frame, highlightbackground='orange', highlightthickness=3, width=1185, height=320)
ratio_table_frame.place(x=325, y=0)
ratio_graph_frame = Frame(ratio_frame, highlightbackground='orange', highlightthickness=3, width=1185, height=350)
ratio_graph_frame.place(x=325, y=325)


root.mainloop()


